### ISSUE TITLE
metoda w klasie do przegladu zupelnego

### ISSUE THREAD

**Issue by JakubKedzierski** [JakubKedzierski/SPD#3]
w środku ma policzyć permutacje 

ma zwracać Cmax oraz kolejność w postaci tablicy 

do środy do zajęć

**Comment by ptroszcz** [comment]
Funkcja przeglądu zupełnego dodana. Testować dla danych zawierających nie więcej niż 10 zadań, ponieważ liczba permutacji rośnie bardzo szybko(dla 20 zadań jest 20! permutacji)
